mj:
  discord:
    guild-id: 1123457943262728234
    channel-id: 1123457943795417130
    user-token: MTA4ODM0MTI2MDU3OTkwOTY2NA.GBM4D-.9LMEaYuuaDtOd4K3wZA1em_4mEn4ve_hfeZ4k8

    session-id: e00d1f4c0d6fdade440c610aba8a5dae
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10