mj:
  discord:
    guild-id: 1123457943262728234
    channel-id: 1123457943795417130
    user-token: MTA4ODM0MTI2MDU3OTkwOTY2NA.GxY5Sl.1EYbJ6Sb_7G9JluSCU4tmeJCHQVpYJwSgwtch4

    session-id: 7d407ce8e591412ddfc8c8b8990fd01c
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
    user-wss: true
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10